export type GeneratedImageDimensions = {
  width: number;
  height: number;
};

export const GENERATED_IMAGE_DIMENSIONS: Record<string, GeneratedImageDimensions> = {
  "/images/assemblies/assembly-axle.webp": { width: 988, height: 991 },
  "/images/assemblies/assembly-brake.webp": { width: 1122, height: 1125 },
  "/images/assemblies/assembly-engine.webp": { width: 647, height: 643 },
  "/images/assemblies/assembly-gearbox.webp": { width: 776, height: 789 },
  "/images/assemblies/assembly-suspension.webp": { width: 1053, height: 1051 },
  "/images/Brake-System.webp": { width: 1200, height: 1200 },
  "/images/brand/certirun-logo-glow.webp": { width: 480, height: 320 },
  "/images/brand/certirunlogo-checkerboard-source.webp": { width: 480, height: 240 },
  "/images/brand/certirunlogo.webp": { width: 480, height: 135 },
  "/images/brands/dfsk.webp": { width: 273, height: 184 },
  "/images/brands/dongfeng.webp": { width: 900, height: 921 },
  "/images/brands/faw.webp": { width: 900, height: 507 },
  "/images/brands/foton.webp": { width: 923, height: 800 },
  "/images/brands/jac.webp": { width: 800, height: 800 },
  "/images/brands/jmc.webp": { width: 648, height: 977 },
  "/images/brands/shacman.webp": { width: 1200, height: 1020 },
  "/images/brands/sinotruk.webp": { width: 1200, height: 1248 },
  "/images/brands/volvo-truck.webp": { width: 480, height: 480 },
  "/images/brands/wuling.webp": { width: 1200, height: 821 },
  "/images/cases/whatsapp-3.webp": { width: 640, height: 1351 },
  "/images/cases/whatsapp-4.webp": { width: 640, height: 1351 },
  "/images/cases/whatsapp-5.webp": { width: 853, height: 1844 },
  "/images/china-industrial-area-aerial.webp": { width: 1200, height: 674 },
  "/images/china-industrial-warehouse.webp": { width: 1200, height: 800 },
  "/images/china-port-containers-sunset.webp": { width: 1200, height: 750 },
  "/images/container-loading-supervision.webp": { width: 1200, height: 803 },
  "/images/Engine-Parts.webp": { width: 1200, height: 675 },
  "/images/factory-quality-inspection-metal-parts.webp": { width: 1200, height: 800 },
  "/images/freight-truck-highway-sunset.webp": { width: 1200, height: 695 },
  "/images/hebei-industrial-park-aerial.webp": { width: 1200, height: 759 },
  "/images/hero-01-highway-transport.webp": { width: 1200, height: 675 },
  "/images/hero-02-commercial-fleet.webp": { width: 1200, height: 675 },
  "/images/hero-03-container-port.webp": { width: 1200, height: 675 },
  "/images/hero-04-logistics-truck.webp": { width: 1200, height: 738 },
  "/images/hero-truck.webp": { width: 1200, height: 738 },
  "/images/industries/hero-electronics-electronic-components.webp": { width: 1200, height: 800 },
  "/images/industries/hero-hardware-products.webp": { width: 1200, height: 800 },
  "/images/industries/hero-machinery-industrial-equipment.webp": { width: 1200, height: 800 },
  "/images/industries/hero-new-energy-pv-ev-parts.webp": { width: 1200, height: 800 },
  "/images/industries/hero-vehicle-parts.webp": { width: 1200, height: 800 },
  "/images/industries/scope/electronics/connectors-and-cables.webp": { width: 640, height: 427 },
  "/images/industries/scope/electronics/consumer-electronic-accessories.webp": { width: 640, height: 427 },
  "/images/industries/scope/electronics/electronic-components.webp": { width: 640, height: 427 },
  "/images/industries/scope/electronics/industrial-electronic-modules.webp": { width: 640, height: 427 },
  "/images/industries/scope/electronics/led-products-and-lighting-parts.webp": { width: 640, height: 427 },
  "/images/industries/scope/electronics/pcb-pcba-related-products.webp": { width: 640, height: 427 },
  "/images/industries/scope/electronics/power-adapters-and-chargers.webp": { width: 640, height: 427 },
  "/images/industries/scope/electronics/sensors-and-switches.webp": { width: 640, height: 427 },
  "/images/industries/scope/energy/battery-related-accessories.webp": { width: 640, height: 427 },
  "/images/industries/scope/energy/dc-switches-and-protection-parts.webp": { width: 640, height: 427 },
  "/images/industries/scope/energy/electric-vehicle-spare-parts.webp": { width: 640, height: 427 },
  "/images/industries/scope/energy/ev-charging-accessories.webp": { width: 640, height: 427 },
  "/images/industries/scope/energy/inverter-accessories.webp": { width: 640, height: 427 },
  "/images/industries/scope/energy/new-energy-installation-hardware.webp": { width: 640, height: 427 },
  "/images/industries/scope/energy/pv-mounting-accessories.webp": { width: 640, height: 427 },
  "/images/industries/scope/energy/solar-cables-and-connectors.webp": { width: 640, height: 427 },
  "/images/industries/scope/hardware/building-hardware.webp": { width: 640, height: 427 },
  "/images/industries/scope/hardware/custom-metal-parts.webp": { width: 640, height: 427 },
  "/images/industries/scope/hardware/fasteners.webp": { width: 640, height: 427 },
  "/images/industries/scope/hardware/hand-tools.webp": { width: 640, height: 427 },
  "/images/industries/scope/hardware/hardware-accessories.webp": { width: 640, height: 427 },
  "/images/industries/scope/hardware/locks-and-hinges.webp": { width: 640, height: 427 },
  "/images/industries/scope/hardware/metal-fittings.webp": { width: 640, height: 427 },
  "/images/industries/scope/hardware/storage-and-workshop-supplies.webp": { width: 640, height: 427 },
  "/images/industries/scope/machinery/agricultural-and-workshop-equipment.webp": { width: 640, height: 427 },
  "/images/industries/scope/machinery/custom-mechanical-parts.webp": { width: 640, height: 427 },
  "/images/industries/scope/machinery/industrial-tools-and-fixtures.webp": { width: 640, height: 427 },
  "/images/industries/scope/machinery/motors-and-reducers.webp": { width: 640, height: 427 },
  "/images/industries/scope/machinery/packaging-machinery.webp": { width: 640, height: 427 },
  "/images/industries/scope/machinery/processing-equipment.webp": { width: 640, height: 427 },
  "/images/industries/scope/machinery/pumps-and-valves.webp": { width: 640, height: 427 },
  "/images/industries/scope/machinery/small-machinery-and-equipment.webp": { width: 640, height: 427 },
  "/images/industries/scope/vehicle/body-and-cabin-parts.webp": { width: 640, height: 427 },
  "/images/industries/scope/vehicle/brake-system-parts.webp": { width: 640, height: 427 },
  "/images/industries/scope/vehicle/bus-parts.webp": { width: 640, height: 427 },
  "/images/industries/scope/vehicle/electrical-parts.webp": { width: 640, height: 427 },
  "/images/industries/scope/vehicle/engine-related-parts.webp": { width: 640, height: 427 },
  "/images/industries/scope/vehicle/passenger-vehicle-replacement-parts.webp": { width: 640, height: 382 },
  "/images/industries/scope/vehicle/suspension-parts.webp": { width: 640, height: 427 },
  "/images/industries/scope/vehicle/trailer-parts.webp": { width: 640, height: 427 },
  "/images/industries/scope/vehicle/truck-parts.webp": { width: 640, height: 427 },
  "/images/insights-hero-collage.webp": { width: 1200, height: 197 },
  "/images/kit/white background axle differential parts flat lay, crown wheel, pinion gear, spider gears, cross shaft, thrust washers, commercial vehicle drivetrain catalog photo, no watermark, square composition.webp": { width: 1083, height: 1085 },
  "/images/kit/white background axle repair kit flat lay, differential bearings, pinion seals, shim sets, gaskets, repair washers, heavy truck axle parts catalog photo, no watermark, square composition.webp": { width: 1077, height: 1078 },
  "/images/kit/white background brake chamber and actuation parts flat lay, brake chamber, slack adjuster, push rod, clevis, repair diaphragm, air brake system parts catalog photo, no watermark, square composition.webp": { width: 1097, height: 1100 },
  "/images/kit/white background brake drum and hardware flat lay, brake drum, wheel studs, brake hardware, anchor pins, mounting kits, truck brake catalog photo, no watermark, square composition.webp": { width: 947, height: 948 },
  "/images/kit/white background brake wear parts flat lay, brake shoes, brake linings, brake pads, return springs, adjuster kits, truck brake parts catalog photo, no watermark, square composition.webp": { width: 1094, height: 1100 },
  "/images/kit/white background clutch and release parts flat lay, clutch disc, pressure plate, release bearing, pilot bearing, clutch fork, clean truck drivetrain catalog photo, no watermark, square composit.webp": { width: 922, height: 929 },
  "/images/kit/white background engine repair kit flat lay, oil seals, gaskets, o-rings, washer sets, seal ring kits, clean industrial catalog photo, no watermark, square composition.webp": { width: 1167, height: 939 },
  "/images/kit/white background engine replacement parts flat lay, water pump, thermostat, sensors, injectors, hoses, commercial vehicle parts catalog style, no watermark, square composition.webp": { width: 882, height: 903 },
  "/images/kit/white background gearbox repair kit flat lay, bearings, oil seals, gaskets, synchronizer parts, needle bearings, clean transmission parts catalog photo, no watermark, square composition.webp": { width: 813, height: 815 },
  "/images/kit/white background gearbox shift and housing parts flat lay, shift fork, selector shaft, housing seals, covers, fastener kits, clean catalog product photo, no watermark, square composition.webp": { width: 927, height: 919 },
  "/images/kit/white background hub and bearing parts flat lay, hub bearings, wheel seals, bearing nuts, lock washers, hub caps, truck wheel end parts catalog photo, no watermark, square composition.webp": { width: 1093, height: 1093 },
  "/images/kit/white background leaf spring parts flat lay, leaf spring, center bolt, spring clips, spring pins, mounting plates, heavy duty suspension parts catalog photo, no watermark, square composition.webp": { width: 960, height: 958 },
  "/images/kit/white background shackle and bushing kit flat lay, shackle kits, bushings, pins, rubber sleeves, grease fittings, commercial vehicle suspension parts catalog photo, no watermark, square composition.webp": { width: 1099, height: 1098 },
  "/images/kit/white background suspension stability components flat lay, U-bolts, torque rod bushings, stabilizer bushes, mount rubbers, hardware kits, heavy truck under chassis parts catalog photo, no watermark, square composition.webp": { width: 1095, height: 1095 },
  "/images/kit/white_background_commercial_vehicle_engine_maintenance_kit_flat_lay_oil_filter_fuel_filter_air_filter_drive_belt_tensioner_clean_catalog_product_photo_no_packaging_no_watermark_square_composition_high_quality_studi.webp": { width: 1024, height: 1024 },
  "/images/logistics transport truck long exposure.webp": { width: 1200, height: 660 },
  "/images/logistics-container-export-port.webp": { width: 1200, height: 674 },
  "/images/logo.webp": { width: 480, height: 480 },
  "/images/page-heroes/about.webp": { width: 1200, height: 800 },
  "/images/page-heroes/cases.webp": { width: 1200, height: 800 },
  "/images/page-heroes/contact.webp": { width: 1200, height: 800 },
  "/images/page-heroes/how-it-works.webp": { width: 1200, height: 600 },
  "/images/page-heroes/services.webp": { width: 1200, height: 675 },
  "/images/page-heroes/whatsapp-1.webp": { width: 1200, height: 800 },
  "/images/page-heroes/whatsapp-2.webp": { width: 1200, height: 800 },
  "/images/platform-downloads/banded/Axle heavy truck 1.webp": { width: 749, height: 468 },
  "/images/platform-downloads/banded/Axle heavy truck 2.webp": { width: 749, height: 428 },
  "/images/platform-downloads/banded/Axle heavy truck 3.webp": { width: 1188, height: 950 },
  "/images/platform-downloads/banded/Axle light truck 1.webp": { width: 1200, height: 1039 },
  "/images/platform-downloads/banded/Axle medium truck 1.webp": { width: 1200, height: 727 },
  "/images/platform-downloads/banded/Brake heavy truck 1.webp": { width: 749, height: 449 },
  "/images/platform-downloads/banded/Brake heavy truck 2.webp": { width: 745, height: 499 },
  "/images/platform-downloads/banded/Brake heavy truck 3.webp": { width: 522, height: 499 },
  "/images/platform-downloads/banded/Brake light truck 1.webp": { width: 749, height: 449 },
  "/images/platform-downloads/banded/Brake medium truck 1.webp": { width: 1200, height: 834 },
  "/images/platform-downloads/banded/Suspension heavy truck 1.webp": { width: 600, height: 540 },
  "/images/platform-downloads/banded/Suspension heavy truck 2.webp": { width: 600, height: 480 },
  "/images/platform-downloads/banded/Suspension heavy truck 3.webp": { width: 1200, height: 900 },
  "/images/platform-downloads/banded/Suspension heavy truck 4.webp": { width: 1200, height: 874 },
  "/images/platform-downloads/banded/Suspension light truck 1.webp": { width: 447, height: 449 },
  "/images/platform-downloads/banded/Suspension medium truck 1.webp": { width: 600, height: 540 },
  "/images/platform-downloads/manual-exact/Engine DFSK DK12-10.webp": { width: 709, height: 709 },
  "/images/platform-downloads/manual-exact/Engine JAC HFC4GB3-3E.webp": { width: 550, height: 550 },
  "/images/platform-downloads/manual-exact/Engine JMC JX4D25B6H.webp": { width: 800, height: 800 },
  "/images/platform-downloads/manual-exact/Engine Liuzhou Wuling LJ4A16QG.webp": { width: 800, height: 800 },
  "/images/platform-downloads/manual-exact/Engine Quanchai 4J28TC.webp": { width: 750, height: 560 },
  "/images/platform-downloads/manual-exact/Engine Quanchai official-q-type.webp": { width: 750, height: 560 },
  "/images/platform-downloads/manual-exact/Engine Quanchai Q25N-152E60.webp": { width: 750, height: 560 },
  "/images/platform-downloads/manual-exact/Engine Sinotruk MC11.40-50.webp": { width: 600, height: 265 },
  "/images/platform-downloads/manual-exact/Engine Sinotruk MC11.44-50.webp": { width: 600, height: 265 },
  "/images/platform-downloads/manual-exact/Engine Yuchai YC4F115-50.webp": { width: 650, height: 488 },
  "/images/platform-downloads/manual-exact/Engine Yunnei D20TCIF16.webp": { width: 550, height: 350 },
  "/images/platform-downloads/manual-exact/Engine Yunnei YN25PLUS160A.webp": { width: 550, height: 350 },
  "/images/platform-downloads/official-batch-2/Axle ZF AxTrax2 closeup 1.webp": { width: 749, height: 468 },
  "/images/platform-downloads/official-batch-2/Axle ZF AxTrax2 longshot 1.webp": { width: 749, height: 428 },
  "/images/platform-downloads/official-batch-2/Axle ZF AxTrax2 longshot 2.webp": { width: 749, height: 422 },
  "/images/platform-downloads/official-batch-2/Brake ZF Brake Chamber.webp": { width: 749, height: 449 },
  "/images/platform-downloads/official-batch-2/Brake ZF TRISTOP D.webp": { width: 745, height: 499 },
  "/images/platform-downloads/official-batch-2/Brake ZF UNISTOP Truck.webp": { width: 522, height: 499 },
  "/images/platform-downloads/official-batch-2/Suspension Hendrickson Center Bushings.webp": { width: 600, height: 306 },
  "/images/platform-downloads/official-batch-2/Suspension Hendrickson Leaf Spring.webp": { width: 600, height: 540 },
  "/images/platform-downloads/official-batch-2/Suspension Hendrickson Torque Rods.webp": { width: 600, height: 480 },
  "/images/platform-downloads/official-batch-3/Axle Hendrickson Composilite EXS20.webp": { width: 1200, height: 727 },
  "/images/platform-downloads/official-batch-3/Axle ZF AxTrax2 Features Graphic.webp": { width: 1200, height: 800 },
  "/images/platform-downloads/official-batch-3/Suspension Hendrickson Airtek NXT Crane.webp": { width: 1200, height: 900 },
  "/images/platform-downloads/official-batch-3/Suspension Hendrickson Softek NXT.webp": { width: 1200, height: 874 },
  "/images/platform-downloads/official-batch-4/Axle Hendrickson Steertek NXT Volvo.webp": { width: 1200, height: 900 },
  "/images/platform-downloads/official-batch-4/Axle Hendrickson TRLAXLE.webp": { width: 1188, height: 950 },
  "/images/platform-downloads/official-batch-4/Suspension Hendrickson Airtek NXT Freightliner.webp": { width: 1200, height: 856 },
  "/images/platform-downloads/official-batch-5/Engine Weichai WP10H family.webp": { width: 550, height: 350 },
  "/images/platform-downloads/official-batch-5/Engine Yuchai YCK11-60 product.webp": { width: 650, height: 488 },
  "/images/platform-downloads/official-batch-5/Engine Yuchai YCY24-60 product.webp": { width: 650, height: 488 },
  "/images/platform-downloads/official-batch-5/Gearbox ZF Ecolite bus.webp": { width: 748, height: 499 },
  "/images/platform-downloads/official-batch-5/Gearbox ZF Ecolite light truck.webp": { width: 748, height: 499 },
  "/images/platform-downloads/official-batch-6/Engine Weichai WP10.5H family.webp": { width: 550, height: 350 },
  "/images/platform-downloads/official-batch-6/Engine Weichai WP2.3Q family.webp": { width: 550, height: 350 },
  "/images/platform-downloads/official-batch-6/Engine Weichai WP3N family.webp": { width: 550, height: 350 },
  "/images/platform-downloads/official-batch-6/Engine Weichai WP4.1N family.webp": { width: 550, height: 350 },
  "/images/platform-downloads/official-batch-6/Engine Weichai WP4.6N family.webp": { width: 550, height: 350 },
  "/images/platform-downloads/official-batch-6/Engine Weichai WP6Q family.webp": { width: 550, height: 350 },
  "/images/platform-downloads/official-batch-6/Engine Weichai WP7 family.webp": { width: 550, height: 350 },
  "/images/platform-downloads/official-batch-6/Engine Weichai WP7H family.webp": { width: 550, height: 350 },
  "/images/platform-downloads/official-batch-6/Engine Weichai WP8 family.webp": { width: 550, height: 350 },
  "/images/platform-downloads/official-batch-6/Engine Weichai WP8Q family.webp": { width: 550, height: 350 },
  "/images/platform-downloads/official-batch-6/Gearbox ZF 6S450P.webp": { width: 748, height: 499 },
  "/images/platform-downloads/official-batch/Engine Cummins ISF3.8.webp": { width: 600, height: 600 },
  "/images/platform-downloads/official-batch/Engine Weichai WP12.430E50 family.webp": { width: 550, height: 350 },
  "/images/platform-downloads/official-batch/Engine Weichai WP2.5NQ180E62 family.webp": { width: 550, height: 350 },
  "/images/platform-downloads/official-batch/Engine Yuchai YCY24-60 family.webp": { width: 650, height: 488 },
  "/images/platform-downloads/official-batch/Gearbox ZF Ecolite.webp": { width: 748, height: 499 },
  "/images/platform-fallbacks/Axle heavy truck 1.webp": { width: 749, height: 468 },
  "/images/platform-fallbacks/Axle light truck 1.webp": { width: 1200, height: 1039 },
  "/images/platform-fallbacks/Axle medium truck 1.webp": { width: 1200, height: 727 },
  "/images/platform-fallbacks/Brake heavy truck 1.webp": { width: 749, height: 449 },
  "/images/platform-fallbacks/Brake light truck 1.webp": { width: 749, height: 449 },
  "/images/platform-fallbacks/Brake medium truck 1.webp": { width: 1200, height: 834 },
  "/images/platform-fallbacks/Engine heavy truck 1.webp": { width: 600, height: 265 },
  "/images/platform-fallbacks/Engine heavy truck 2.webp": { width: 550, height: 350 },
  "/images/platform-fallbacks/Engine light truck 1.webp": { width: 800, height: 800 },
  "/images/platform-fallbacks/Engine light truck 2.webp": { width: 550, height: 350 },
  "/images/platform-fallbacks/Engine medium truck 1.webp": { width: 550, height: 350 },
  "/images/platform-fallbacks/Engine medium truck 2.webp": { width: 550, height: 350 },
  "/images/platform-fallbacks/Gearbox light truck 1.webp": { width: 748, height: 499 },
  "/images/platform-fallbacks/Gearbox light truck 2.webp": { width: 748, height: 499 },
  "/images/platform-fallbacks/Gearbox medium truck 1.webp": { width: 748, height: 499 },
  "/images/platform-fallbacks/Gearbox medium truck 2.webp": { width: 748, height: 499 },
  "/images/platform-fallbacks/Suspension heavy truck 1.webp": { width: 600, height: 540 },
  "/images/platform-fallbacks/Suspension light truck 1.webp": { width: 447, height: 449 },
  "/images/platform-fallbacks/Suspension medium truck 1.webp": { width: 600, height: 540 },
  "/images/platform-library/air-system/air-candidate-1.webp": { width: 223, height: 550 },
  "/images/platform-library/air-system/air-candidate-2.webp": { width: 550, height: 550 },
  "/images/platform-library/axle/fallback/Axle heavy truck 1.webp": { width: 749, height: 468 },
  "/images/platform-library/axle/fallback/Axle heavy truck 2.webp": { width: 749, height: 428 },
  "/images/platform-library/axle/fallback/Axle heavy truck 3.webp": { width: 1188, height: 950 },
  "/images/platform-library/axle/fallback/Axle light truck 1.webp": { width: 1200, height: 1039 },
  "/images/platform-library/axle/fallback/Axle medium truck 1.webp": { width: 1200, height: 727 },
  "/images/platform-library/axle/hendrickson/Axle Hendrickson Composilite EXS20.webp": { width: 1200, height: 727 },
  "/images/platform-library/axle/hendrickson/Axle Hendrickson Steertek NXT Volvo.webp": { width: 1200, height: 900 },
  "/images/platform-library/axle/hendrickson/Axle Hendrickson TRLAXLE.webp": { width: 1188, height: 950 },
  "/images/platform-library/axle/zf/Axle ZF AxTrax2 closeup 1.webp": { width: 749, height: 468 },
  "/images/platform-library/axle/zf/Axle ZF AxTrax2 Features Graphic.webp": { width: 1200, height: 800 },
  "/images/platform-library/axle/zf/Axle ZF AxTrax2 longshot 1.webp": { width: 749, height: 428 },
  "/images/platform-library/axle/zf/Axle ZF AxTrax2 longshot 2.webp": { width: 749, height: 422 },
  "/images/platform-library/brake/fallback/Brake heavy truck 1.webp": { width: 749, height: 449 },
  "/images/platform-library/brake/fallback/Brake heavy truck 2.webp": { width: 745, height: 499 },
  "/images/platform-library/brake/fallback/Brake heavy truck 3.webp": { width: 522, height: 499 },
  "/images/platform-library/brake/fallback/Brake light truck 1.webp": { width: 749, height: 449 },
  "/images/platform-library/brake/fallback/Brake medium truck 1.webp": { width: 1200, height: 834 },
  "/images/platform-library/brake/zf/Brake ZF Brake Chamber.webp": { width: 749, height: 449 },
  "/images/platform-library/brake/zf/Brake ZF TRISTOP D.webp": { width: 745, height: 499 },
  "/images/platform-library/brake/zf/Brake ZF UNISTOP Truck.webp": { width: 522, height: 499 },
  "/images/platform-library/electrical/electrical-candidate-1.webp": { width: 346, height: 451 },
  "/images/platform-library/electrical/electrical-candidate-2.webp": { width: 578, height: 271 },
  "/images/platform-library/electrical/electrical-candidate-3.webp": { width: 841, height: 463 },
  "/images/platform-library/electrical/electrical-candidate-4.webp": { width: 195, height: 178 },
  "/images/platform-library/electrical/electrical-candidate-5.webp": { width: 620, height: 831 },
  "/images/platform-library/electrical/electrical-candidate-6.webp": { width: 793, height: 347 },
  "/images/platform-library/electrical/electrical-candidate-7.webp": { width: 765, height: 818 },
  "/images/platform-library/electrical/electrical-candidate-8.webp": { width: 641, height: 305 },
  "/images/platform-library/electrical/electrical-candidate-9.webp": { width: 858, height: 502 },
  "/images/platform-library/engine/cummins/Engine Cummins ISF3.8.webp": { width: 600, height: 600 },
  "/images/platform-library/engine/dfsk/Engine DFSK DK12-10.webp": { width: 709, height: 709 },
  "/images/platform-library/engine/dongan/Engine Dongan DAM15R.webp": { width: 797, height: 797 },
  "/images/platform-library/engine/fallback/Engine heavy truck 1.webp": { width: 600, height: 265 },
  "/images/platform-library/engine/fallback/Engine heavy truck 2.webp": { width: 550, height: 350 },
  "/images/platform-library/engine/fallback/Engine light truck 1.webp": { width: 650, height: 488 },
  "/images/platform-library/engine/fallback/Engine light truck 2.webp": { width: 550, height: 350 },
  "/images/platform-library/engine/fallback/Engine light truck 3.webp": { width: 550, height: 350 },
  "/images/platform-library/engine/fallback/Engine light truck 4.webp": { width: 550, height: 350 },
  "/images/platform-library/engine/fallback/Engine light truck 5.webp": { width: 650, height: 488 },
  "/images/platform-library/engine/fallback/Engine medium truck 1.webp": { width: 550, height: 350 },
  "/images/platform-library/engine/fallback/Engine medium truck 2.webp": { width: 550, height: 350 },
  "/images/platform-library/engine/jac/Engine JAC HFC4GB3-3E.webp": { width: 550, height: 550 },
  "/images/platform-library/engine/liuji/Engine Liuzhou Wuling LJ4A16QG.webp": { width: 800, height: 800 },
  "/images/platform-library/engine/quanchai/Engine Quanchai 4J28TC.webp": { width: 750, height: 560 },
  "/images/platform-library/engine/quanchai/Engine Quanchai official-q-type.webp": { width: 750, height: 560 },
  "/images/platform-library/engine/quanchai/Engine Quanchai Q25N-152E60.webp": { width: 750, height: 560 },
  "/images/platform-library/engine/sinotruk/Engine Sinotruk MC11.40-50.webp": { width: 600, height: 265 },
  "/images/platform-library/engine/sinotruk/Engine Sinotruk MC11.44-50.webp": { width: 600, height: 265 },
  "/images/platform-library/engine/weichai/Engine Weichai WP10.5H family.webp": { width: 550, height: 350 },
  "/images/platform-library/engine/weichai/Engine Weichai WP10H family.webp": { width: 550, height: 350 },
  "/images/platform-library/engine/weichai/Engine Weichai WP12.430E50 family.webp": { width: 550, height: 350 },
  "/images/platform-library/engine/weichai/Engine Weichai WP2.3Q family.webp": { width: 550, height: 350 },
  "/images/platform-library/engine/weichai/Engine Weichai WP2.5NQ180E62 family.webp": { width: 550, height: 350 },
  "/images/platform-library/engine/weichai/Engine Weichai WP3N family.webp": { width: 550, height: 350 },
  "/images/platform-library/engine/weichai/Engine Weichai WP4.1N family.webp": { width: 550, height: 350 },
  "/images/platform-library/engine/weichai/Engine Weichai WP4.6N family.webp": { width: 550, height: 350 },
  "/images/platform-library/engine/weichai/Engine Weichai WP6Q family.webp": { width: 550, height: 350 },
  "/images/platform-library/engine/weichai/Engine Weichai WP7 family.webp": { width: 550, height: 350 },
  "/images/platform-library/engine/weichai/Engine Weichai WP7H family.webp": { width: 550, height: 350 },
  "/images/platform-library/engine/weichai/Engine Weichai WP8 family.webp": { width: 550, height: 350 },
  "/images/platform-library/engine/weichai/Engine Weichai WP8Q family.webp": { width: 550, height: 350 },
  "/images/platform-library/engine/yuchai/Engine Yuchai YC4F115-50.webp": { width: 650, height: 488 },
  "/images/platform-library/engine/yuchai/Engine Yuchai YCK11-60 product.webp": { width: 650, height: 488 },
  "/images/platform-library/engine/yuchai/Engine Yuchai YCY24-60 family.webp": { width: 650, height: 488 },
  "/images/platform-library/engine/yuchai/Engine Yuchai YCY24-60 product.webp": { width: 650, height: 488 },
  "/images/platform-library/engine/yuchai/Engine Yuchai YCY24155-61.webp": { width: 650, height: 488 },
  "/images/platform-library/engine/yunnei/Engine Yunnei D20TCIF16.webp": { width: 550, height: 350 },
  "/images/platform-library/engine/yunnei/Engine Yunnei YN25PLUS160A.webp": { width: 550, height: 350 },
  "/images/platform-library/gearbox/fallback/Gearbox light truck 1.webp": { width: 748, height: 499 },
  "/images/platform-library/gearbox/fallback/Gearbox light truck 2.webp": { width: 748, height: 499 },
  "/images/platform-library/gearbox/fallback/Gearbox medium truck 1.webp": { width: 748, height: 499 },
  "/images/platform-library/gearbox/fallback/Gearbox medium truck 2.webp": { width: 748, height: 499 },
  "/images/platform-library/gearbox/zf/Gearbox ZF 6S450P.webp": { width: 748, height: 499 },
  "/images/platform-library/gearbox/zf/Gearbox ZF Ecolite bus.webp": { width: 748, height: 499 },
  "/images/platform-library/gearbox/zf/Gearbox ZF Ecolite light truck.webp": { width: 748, height: 499 },
  "/images/platform-library/gearbox/zf/Gearbox ZF Ecolite.webp": { width: 748, height: 499 },
  "/images/platform-library/suspension/fallback/Suspension heavy truck 1.webp": { width: 600, height: 540 },
  "/images/platform-library/suspension/fallback/Suspension heavy truck 2.webp": { width: 600, height: 480 },
  "/images/platform-library/suspension/fallback/Suspension heavy truck 3.webp": { width: 1200, height: 900 },
  "/images/platform-library/suspension/fallback/Suspension heavy truck 4.webp": { width: 1200, height: 874 },
  "/images/platform-library/suspension/fallback/Suspension light truck 1.webp": { width: 447, height: 449 },
  "/images/platform-library/suspension/fallback/Suspension medium truck 1.webp": { width: 600, height: 540 },
  "/images/platform-library/suspension/hendrickson/Suspension Hendrickson Airtek NXT Crane.webp": { width: 1200, height: 900 },
  "/images/platform-library/suspension/hendrickson/Suspension Hendrickson Airtek NXT Freightliner.webp": { width: 1200, height: 856 },
  "/images/platform-library/suspension/hendrickson/Suspension Hendrickson Center Bushings.webp": { width: 600, height: 306 },
  "/images/platform-library/suspension/hendrickson/Suspension Hendrickson Leaf Spring.webp": { width: 600, height: 540 },
  "/images/platform-library/suspension/hendrickson/Suspension Hendrickson Softek NXT.webp": { width: 1200, height: 874 },
  "/images/platform-library/suspension/hendrickson/Suspension Hendrickson Torque Rods.webp": { width: 600, height: 480 },
  "/images/port-container-loading-night.webp": { width: 1200, height: 801 },
  "/images/shipping-documents-export-paperwork.webp": { width: 1200, height: 783 },
  "/images/social/container-consolidation-series/01-traditional-buying-friction.webp": { width: 1200, height: 800 },
  "/images/social/container-consolidation-series/02-container-consolidation.webp": { width: 1200, height: 800 },
  "/images/social/container-consolidation-series/03-balanced-sku-sourcing.webp": { width: 1200, height: 800 },
  "/images/social/container-consolidation-series/04-cost-and-inventory-efficiency.webp": { width: 1200, height: 1800 },
  "/images/sourcing/advantage-inventory-worker.webp": { width: 1200, height: 800 },
  "/images/sourcing/advantage-warehouse-shelves.webp": { width: 1200, height: 1800 },
  "/images/sourcing/balanced-sku-inventory.webp": { width: 1200, height: 800 },
  "/images/sourcing/compare-container-ship.webp": { width: 1200, height: 800 },
  "/images/sourcing/compare-warehouse-team.webp": { width: 1200, height: 800 },
  "/images/sourcing/comparison-logic-team.webp": { width: 1200, height: 800 },
  "/images/sourcing/friction-container-yard.webp": { width: 1200, height: 800 },
  "/images/sourcing/friction-port-topview.webp": { width: 1200, height: 800 },
  "/images/sourcing/traditional-buying-friction.webp": { width: 1200, height: 800 },
  "/images/Suspension.webp": { width: 1200, height: 675 },
  "/images/testimonials/jack.webp": { width: 1200, height: 1200 },
  "/images/testimonials/kingsley.webp": { width: 1024, height: 1536 },
};
